# Generated by Django 2.2.6 on 2019-10-30 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Events_name', models.CharField(max_length=200)),
                ('tickets_count', models.IntegerField()),
                ('info', models.TextField()),
                ('img', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TimeTable.Category')),
            ],
        ),
    ]
