# Generated by Django 2.2.6 on 2019-10-30 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='Events_name',
            new_name='events_name',
        ),
    ]
