# Generated by Django 2.2.6 on 2019-10-30 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TimeTable', '0002_auto_20191030_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tickets_count', models.IntegerField()),
                ('price', models.IntegerField()),
                ('event', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TimeTable.Event')),
                ('order_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
