# Generated by Django 2.2.6 on 2019-10-30 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0003_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_user',
            new_name='order_user1',
        ),
    ]
