# Generated by Django 2.2.6 on 2019-10-30 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0004_auto_20191030_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_user1',
            new_name='order_user',
        ),
    ]
