# Generated by Django 2.2.6 on 2019-11-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0005_auto_20191030_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='img',
            field=models.CharField(max_length=1000),
        ),
    ]
