# Generated by Django 2.2.6 on 2019-11-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0007_auto_20191123_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='geolocation',
            field=models.CharField(default='', max_length=200),
        ),
    ]
