# Generated by Django 2.2.6 on 2019-11-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0010_auto_20191128_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='img',
            field=models.ImageField(upload_to='img'),
        ),
    ]
