# Generated by Django 2.2.6 on 2019-11-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0011_auto_20191128_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(default=True, upload_to='category'),
        ),
    ]
