# Generated by Django 2.2.6 on 2019-12-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0012_auto_20191130_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(upload_to='category'),
        ),
    ]
